{% set name = "torch-frft" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torch_frft-{{ version }}.tar.gz
  sha256: 4ec3061d2938bb2dc3153b7caf2f502cec551594363266667ef9691763dcef9f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.13
    - pip
  run:
    - python >=3.10,<3.13
    - numpy >=1.22.4,<=2.1.0
    - pytorch >=2.0.0
    - scipy >=1.13.1

test:
  imports:
    - torch_frft
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tunakasif/torch-frft
  summary: PyTorch implementation of the fractional Fourier transform with trainable transform order.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tunakasif
