{% set python_min = '3.10' %}
{% set name = "torch-frft" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torch_frft-{{ version }}.tar.gz
  sha256: 9926b92437831c8522028f7da90334816eafba5ad303c51eaf85f9f505fe2fda

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<3.12
    - numpy >=1.24.3,<2.0.0
    - scipy >=1.10.1,<2.0.0
    - pytorch >=2.0.0,<2.0.1

test:
  imports:
    - torch_frft
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tunakasif/torch-frft
  summary: PyTorch implementation of the fractional Fourier transform with trainable transform order.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tunakasif
